theme: jekyll-theme-primer
title: Vector Watcher
description: "Vector Watcher is a cross-platform desktop application for vector database monitoring, debugging, and analytics across Linux, macOS, and Windows."

# Absolute URL settings (Required for WhatsApp & Social Cards)
url: "https://recursivezero.github.io"
baseurl: "/vector-watcher"

# Open Graph & SEO Configuration
logo: /screenshots/og-cover.png # Used as default image preview
social:
  name: Recursive Zero
  links:
    - https://github.com/recursivezero

# Enable GitHub Pages built-in plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Enable GFM code highlighting and auto TOC support
kramdown:
  input: GFM
  syntax_highlighter: rouge
