name: Build Linux Snap

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: Build Snap
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Snapcraft
        run: |
          sudo snap install snapcraft --classic

      - name: Verify Snapcraft
        run: |
          snapcraft --version

      - name: Setup LXD
        uses: canonical/setup-lxd@main
        with:
          channel: 5.21/stable

      - name: Build Snap
        run: |
          snapcraft pack

      - name: Verify Snap artifact
        run: |
          find . -maxdepth 2 -type f -name "*.snap" -exec ls -lh {} \;

      - name: Upload Snap artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: vector-watcher-snap
          path: "*.snap"
