name: "Comment on Issue"

run-name: "Comment under an Issue"

on:
  issues:
    types:
      - opened
  workflow_dispatch:
    inputs:
      comment-body:
        description: "Comment text"
        required: true
        type: string
      issue-number:
        description: "Issue number"
        required: true
        type: number

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Run Comment Action
        uses: recursivezero/action-club/.github/actions/comment-on-issue@v0.2.67
        with:
          comment_body: ${{ github.event.inputs.comment-body }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.inputs.issue-number }}
