name: Issue Sync with Branch
run-name: notify whenever a branch created using issue title

on:
  create: # Triggers when a branch or tag is created

permissions:
  issues: write # Required to comment and add labels
  contents: read # Required to read the repo metadata

jobs:
  notify:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Link Branch to Issue
        uses: recursivezero/action-club/.github/actions/branch-notify@v0.2.67
        with:
          issue_prefix: ${{ vars.PROJECT_PREFIX }}
          branch_name: ${{ github.event.ref }}
